# Generated by Django 2.0.2 on 2018-02-05 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myDate', models.CharField(max_length=200, verbose_name='العصر')),
            ],
            options={
                'verbose_name_plural': 'العصر',
            },
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان القصيدة')),
                ('myDate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Search.MyDate', verbose_name='العصر')),
            ],
            options={
                'verbose_name_plural': 'القصيدة',
            },
        ),
        migrations.CreateModel(
            name='Poet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(max_length=200, verbose_name='عنوان الصورة')),
                ('name', models.CharField(max_length=200, verbose_name='الشاعر')),
            ],
            options={
                'verbose_name_plural': 'الشاعر',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='دار النشر')),
            ],
            options={
                'verbose_name_plural': 'دار النشر',
            },
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=200, verbose_name='الغرض')),
            ],
            options={
                'verbose_name_plural': 'الغرض',
            },
        ),
        migrations.CreateModel(
            name='Sea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sea', models.CharField(max_length=200, verbose_name='البحر')),
            ],
            options={
                'verbose_name_plural': 'بحر القصيدة',
            },
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='البيت')),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Search.Poem', verbose_name='عنوان القصيدة')),
            ],
            options={
                'verbose_name_plural': 'بيت القصيدة',
            },
        ),
        migrations.AddField(
            model_name='poem',
            name='poet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Search.Poet', verbose_name='الشاعر'),
        ),
        migrations.AddField(
            model_name='poem',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Search.Publisher', verbose_name='دار النشر'),
        ),
        migrations.AddField(
            model_name='poem',
            name='purpose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Search.Purpose', verbose_name='الغرض'),
        ),
        migrations.AddField(
            model_name='poem',
            name='sea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Search.Sea', verbose_name='البحر'),
        ),
    ]
